# Multi-stage starter template for:
# -Building the solution when changes to the contents of the solution folder are triggered (see trigger-SolutionName.yml for example trigger)
# -Deploying the solution to a specific environment based on pipeline variables
# This is most commonly used for PR Validation where both the build and deploy must suceeed in order for the PR checks to succeed.

parameters:
- name: importUnmanaged
  type: boolean
  default: false
- name: overwriteUnmanagedCustomizations
  type: boolean
  default: false
- name: alignDev
  type: boolean
  default: false

stages:
- stage: preBuild
  displayName: 'Align Dev with Git Repo' 
  condition: eq(${{parameters.alignDev}}, true)
  jobs:
  - job: preBuild
    pool: 
      vmImage: 'windows-latest'
    steps:
    - template: unpack-solution.yml
      parameters:
        branch: $(Build.SourceBranchName) #SHOULD BE THE SPRINT/FEATURE BRANCH
        commitMessage: 'Solution package updated as part of deployment process'
        email: $(Build.RequestedForEmail)
        serviceConnection: $(EnvironmentUrl) #SHOULD BE THE SPRINT/FEATURE ENVIRONMENT
        solutionName: $(SolutionName) 
        userName: $(Build.RequestedFor)
- stage: build
  displayName: 'Build'
  dependsOn: preBuild
  condition: in(dependencies.preBuild.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
  jobs:
  - job: build
    pool: 
      vmImage: 'windows-latest'
    steps:
    - template: build-solution.yml
      parameters:
        buildType: 'Both'
        mapCodeComponents: true
        exportManaged: true
- stage: deployDev
  displayName: 'Deploy to Dev'
  dependsOn: build
  condition: and(in(dependencies.build.result, 'Succeeded', 'SucceededWithIssues'), eq(${{parameters.alignDev}}, true))
  jobs:
  - job: deploy
    pool: 
      vmImage: 'windows-latest'
    steps:
    - template: deploy-solution.yml
      parameters:
        serviceConnection: '$(EnvironmentUrl)'
        importUnmanaged: ${{parameters.importUnmanaged}}
        overwriteUnmanagedCustomizations: ${{parameters.overwriteUnmanagedCustomizations}}
- stage: deployTst
  displayName: 'Deploy to Test'
  dependsOn: deployDev
  condition: in(dependencies.build.result, 'Succeeded', 'SucceededWithIssues')
  jobs:
  - job: deploy
    pool: 
      vmImage: 'windows-latest'
    steps:
    - template: deploy-solution.yml
      parameters:
        serviceConnection: 'https://$(TestEnvironmentName).crm4.dynamics.com/'
        importUnmanaged: false
        overwriteUnmanagedCustomizations: ${{parameters.overwriteUnmanagedCustomizations}}
        importCommonData: true
        importEnvSpecificData: true