parameters:
- name: environmentName
  type: string
steps:
  #Check for deployment settings for this environment
- powershell: |
    $settingFile = "deployment-settings.json"
    $deploymentSettingsPath = ''
    $path = "$(Build.SourcesDirectory)\Configuration\${{parameters.environmentName}}\$settingFile"
    if(Test-Path $path)
    {
      $deploymentSettingsPath = $path
    }

    Write-Host "##vso[task.setVariable variable=DeploymentSettingsPath]$deploymentSettingsPath"
    $useDeploymentSettings = 'false'
    if($deploymentSettingsPath -ne '') {
      $useDeploymentSettings = 'true'
    }
    Write-Host "##vso[task.setVariable variable=UseDeploymentSettings]$useDeploymentSettings"
  displayName: 'Check if Deployment Settings Exist'