trigger: none
pr: none
    
name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

variables:
- group: dev-scope
- group: project-scope

pool:
  name: Azure Pipelines
  vmImage: windows-latest

stages:
- template: Templates\build-deploy-solution-to-env.yml@PipelineRepo