trigger:
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - $(SolutionName)
  paths:
# Replace 'SolutionFolderInBranch' with actual folder name in repo (i.e. this will be the folder that contains your unpacked solution. In the case where you are using a repo per solution you may not need to specify this value)
    include: # Add any additional paths to include (e.g. SampleSolutionName/PCFControls etc.)
    - $(SolutionName)/ # Replace SolutionFolder with actual folder name in repo
    - $(SolutionName)/Plugins/ # Replace SolutionFolder with actual folder name in repo
    - $(SolutionName)/WebResources/ # Replace SolutionFolder with actual folder name in repo
    
name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline. The group specified below is a variable group defined in the Library for the Pipelines
variables:
- group: project-scope
- group: dev-scope

parameters:
- name: buildType
  type: string
  default: 'Both'
  values:
  - Both
  - Managed
  - Unmanaged

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildjob
    pool: 
      vmImage: 'windows-latest'
    steps:
    - template: Templates\build-solution.yml
      parameters:
        buildType: ${{parameters.buildType}}