# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Create Azure Function App
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Service connection - Non Production'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az functionapp create --location westeurope --name azdbdpeuwfuncsherlock001 --storage-account azdbdpeuwstsherlock001 --resource-group azdbdpeuw-rg-sherlock001 --tags Region=EUN Environment=DEV CostCenter=TBD CostResponsible=TBD Country=TBD'
