# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
- script: echo Create Azure Function App
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azabdp-sc-main-001'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --location westeurope --name sherlock004 --tags Region=EUN Environment=Dev CostCenter=TBD CostResponsible=TBD Country=TBD'
