trigger:
- none

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'Azure Service connection - Non Production'
  appName: 'azdtdpeuw-func-sherlock-001'
  # Agent VM image name
  vmImageName: 'windows-latest'
steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure Service connection - Non Production'
    appType: 'functionApp'
    appName: $(appName)
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'