trigger:
- none

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'Azure Service connection - Non Production'
  appName: 'azabdp-sc-main-001'
  # Agent VM image name
  vmImageName: 'windows-latest'
steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'azabdp-sc-main-001'
    appType: 'functionApp'
    appName: 'azdbdpeuw-func-sherlock-006'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'