trigger:
- none

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'Azure Service connection - Non Production'
  appName: 'azdbdpeuw-func-sherlock-001'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: $(azureSubscription)
    appType: functionApp # default is functionApp
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
    #Uncomment the next lines to deploy to a deployment slot
    #Note that deployment slots is not supported for Linux Dynamic SKU
    #deployToSlotOrASE: true
    #resourceGroupName: '<Resource Group Name>'
    #slotName: '<Slot name>'